print("Добро пожаловать в калькулятор! ")
number_1 = int (input ('Введите ваше первое число: '))
number_2 = int (input ('Введите ваше второе число: '))
print ('{} + {} = '.format (number_1, number_2))
print (number_1 + number_2)